name: Push Tenant 2 DAGs to S3

on:
  push:
    branches: [ "main" ]

jobs:
  push-dags:
    runs-on: ubuntu-latest
    env:
      S3_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
      S3_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      S3_ENDPOINT_URL: ${{ secrets.S3_ENDPOINT_URL }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install s4cmd
        run: |
          pip install s4cmd
      
      # - name: Validate DAGs
      #   run: |
      #     pip install apache-airflow
      #     airflow dags validate dags/tenant1_dag.py

      - name: Push DAGs to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          s4cmd put dags/tenant2_dag.py s3://dags/tenant2/tenant2_dag.py --endpoint-url=$S3_ENDPOINT_URL
